steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    dir: "api"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sendook-api:$TAG_NAME"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sendook-api:latest"
      - "."

  # Push images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "--all-tags", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sendook-api"]

  # Get GKE credentials
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["container", "clusters", "get-credentials", "${_GKE_CLUSTER}", "--region=${_REGION}"]

  # Replace placeholder and deploy
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed -i "s|IMAGE_PLACEHOLDER|${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sendook-api:$TAG_NAME|g" api/k8s/deployment.yaml
        kubectl apply -f api/k8s/
    env: ["CLOUDSDK_COMPUTE_REGION=${_REGION}", "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sendook-api:$TAG_NAME"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sendook-api:latest"
